apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
  {{- include "flaskapp.labels" . | nindent 4 }}
  name: flaskapp
spec:
  host: ""
  port:
    targetPort: {{ .Values.service.targetPort }}
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "flaskapp.fullname" . }}
    weight: 100
  wildcardPolicy: None